"use client";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Bot, Sparkles, Quote } from "lucide-react";
import { PageHeader, LinkButton, AIDisclaimer, RiskBadge, Badge, ScoreRing, scoreColor } from "@/components/ui";
import { rankedForProblem } from "@/mock/govExtra";
import { cn } from "@/lib/format";
import { StartupAvatar } from "@/components/gov/StartupAvatar";

export default function AIRecommendation() {
  const top = rankedForProblem("plastic-recycling").slice(0, 5);
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="AI-generated · Plastic Recycling"
        title="AI Recommendation"
        subtitle="This screen shows only what the AI agents produced. No human decision has been made yet."
        actions={<LinkButton href="/government/human-review" variant="saffron">Send to Human Review <ArrowRight className="h-4 w-4" /></LinkButton>}
      />
      <div className="relative overflow-hidden rounded-2xl border-2 border-dashed border-ai-400/40 bg-ai-500/[0.05] px-6 py-5 text-center">
        <p className="flex items-center justify-center gap-2 font-display text-xl font-bold tracking-[0.12em] text-ai-300 md:text-2xl"><Bot className="h-7 w-7" /> AI RECOMMENDATION — NOT FINAL DECISION</p>
        <p className="mt-1 text-sm text-slate-400">Top 5 of 48 applications, ranked on predefined criteria. Selection, contracts and payments require human approval.</p>
      </div>

      <div className="space-y-4">
        {top.map((r, i) => {
          const b = Object.fromEntries(r.ev.breakdown.map((x) => [x.key, x]));
          return (
            <motion.div key={r.app.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.07 }}
              className={cn("glass glass-hover grid gap-5 p-5 lg:grid-cols-[auto_1fr_auto] lg:items-center", i === 0 && "glow-border")}>
              <div className="flex items-center gap-4">
                <div className={cn("grid h-14 w-14 place-items-center rounded-2xl font-display text-2xl font-bold",
                  i === 0 ? "bg-setu-gradient text-ink-950" : "bg-white/[0.04] text-slate-300 ring-1 ring-white/10")}># {r.rank}</div>
                <StartupAvatar name={r.startup.name} size="lg" />
                <div className="lg:w-52">
                  <Link href={`/government/applications/${r.app.id}`} className="font-display text-lg font-semibold text-white hover:text-setu-200">{r.startup.name}</Link>
                  <div className="mt-1 flex flex-wrap gap-1.5"><RiskBadge risk={r.ev.risk} /><Badge tone="ai">{r.ev.confidence}% confidence</Badge></div>
                </div>
              </div>
              <div>
                <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                  {(["fit", "feasibility", "track", "scalability"] as const).map((k) => (
                    <div key={k} className="rounded-xl border border-white/[0.05] bg-white/[0.02] p-2.5" title={b[k].reason}>
                      <p className="text-[11px] text-slate-500">{b[k].label}</p>
                      <p className="font-display text-xl font-semibold" style={{ color: scoreColor(b[k].score) }}>{b[k].score}</p>
                    </div>
                  ))}
                </div>
                <p className="mt-3 flex items-start gap-2 text-sm text-slate-300"><Quote className="mt-0.5 h-4 w-4 shrink-0 text-ai-400" /><span><span className="font-medium text-ai-300">Key reason: </span>{r.ev.keyReason}</span></p>
              </div>
              <div className="flex items-center gap-4 lg:flex-col">
                <ScoreRing score={r.ev.overall} size={96} stroke={8} label="Overall" />
                <Link href={`/government/applications/${r.app.id}`} className="text-xs text-setu-300 hover:underline">Full reasoning →</Link>
              </div>
            </motion.div>
          );
        })}
      </div>
      <AIDisclaimer><Sparkles className="mr-1 inline h-3.5 w-3.5" />Generated by 7 AI agents on 02 Oct 2026, 09:15. Next step: an expert panel scores the top 5 and an authorised officer makes the final decision.</AIDisclaimer>
    </div>
  );
}
